from typing import Protocol

from app.domain.org.entities import Member, Organization, RoleProfile, Team


class IOrganizationRepository(Protocol):
    async def create(self, org: Organization) -> None: ...

    async def get_by_id(self, org_id: str) -> Organization | None: ...

    async def list_all(self) -> list[Organization]: ...

    async def update(self, org: Organization) -> None: ...

    async def delete(self, org_id: str) -> None: ...


class ITeamRepository(Protocol):
    async def create(self, team: Team) -> None: ...

    async def get_by_id(self, team_id: str) -> Team | None: ...

    async def update(self, team: Team) -> None: ...

    async def delete(self, team_id: str) -> None: ...


class IMemberRepository(Protocol):
    async def create(self, member: Member) -> None: ...

    async def get_by_id(self, member_id: str) -> Member | None: ...

    async def update(self, member: Member) -> None: ...

    async def delete(self, member_id: str) -> None: ...


class IRoleProfileRepository(Protocol):
    async def list_all(self) -> list[RoleProfile]: ...

    async def get_by_id(self, role_profile_id: str) -> RoleProfile | None: ...

    async def upsert(self, profile: RoleProfile) -> None: ...
