"""initial schema

Revision ID: 4b837ea61cc8
Revises:
Create Date: 2026-03-27 22:07:41.537024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b837ea61cc8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("default_phase_ratios", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin", "pm", "tech_lead", "member", name="user_role", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_org_id"), ["org_id"], unique=False)

    op.create_table(
        "personnel",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column(
            "seniority",
            sa.Enum(
                "intern",
                "junior",
                "mid",
                "senior",
                "lead",
                name="seniority_level",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("base_wfu", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("daily_capacity_hours", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("hourly_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("velocity_baseline", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("dreyfus_level", sa.SmallInteger(), nullable=True),
        sa.Column("github_username", sa.String(length=100), nullable=True),
        sa.Column("profile_last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personnel", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_personnel_org_id"), ["org_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "planning",
                "execution",
                "completed",
                "cancelled",
                name="project_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deadline", sa.Date(), nullable=False),
        sa.Column("budget_total", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("budget_currency", sa.String(length=10), nullable=False),
        sa.Column("active_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("phase_ratios_override", sa.JSON(), nullable=True),
        sa.Column("raw_proposal", sa.Text(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "evaluation_status",
            sa.Enum(
                "not_started",
                "in_progress",
                "complete",
                "waived",
                name="evaluation_workflow_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_org_id"), ["org_id"], unique=False)

    op.create_table(
        "personnel_languages",
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column(
            "proficiency",
            sa.Enum(
                "native",
                "fluent",
                "basic",
                name="language_proficiency",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personnel_languages", schema=None) as batch_op:
        batch_op.create_index("idx_personnel_languages", ["personnel_id"], unique=False)

    op.create_table(
        "personnel_profiles",
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version", sa.String(length=20), nullable=False),
        sa.Column("data_period_from", sa.Date(), nullable=False),
        sa.Column("data_period_to", sa.Date(), nullable=False),
        sa.Column("corpus_size", sa.Integer(), nullable=False),
        sa.Column("ocean_scores", sa.JSON(), nullable=False),
        sa.Column("behavioral_prefs", sa.JSON(), nullable=False),
        sa.Column("tech_capability", sa.JSON(), nullable=False),
        sa.Column("soft_skills", sa.JSON(), nullable=False),
        sa.Column("performance", sa.JSON(), nullable=False),
        sa.Column("wfu_factors", sa.JSON(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("github_repos_analyzed", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("personnel_id", name="uq_personnel_profiles_personnel"),
    )
    op.create_table(
        "project_evaluations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "complete", name="evaluation_status", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "verdict",
            sa.Enum(
                "proceed",
                "conditional",
                "do_not_proceed",
                name="evaluation_verdict",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("composite_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("axis_scores", sa.JSON(), nullable=False),
        sa.Column("telos_breakdown", sa.JSON(), nullable=False),
        sa.Column("risk_register", sa.JSON(), nullable=False),
        sa.Column("axis_weights", sa.JSON(), nullable=False),
        sa.Column("llm_session_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", name="uq_project_evaluations_project"),
    )
    op.create_table(
        "project_memberships",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("role_in_project", sa.String(length=100), nullable=False),
        sa.Column("joined_at", sa.Date(), nullable=False),
        sa.Column("left_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "allocation_pct > 0 AND allocation_pct <= 100",
            name="valid_project_membership_allocation",
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_memberships_personnel_id"), ["personnel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_project_memberships_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "project_team_matches",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("skill_coverage_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("ocean_fit_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("growth_opportunity_score", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("effective_wfu_estimate", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("match_details", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_team_matches", schema=None) as batch_op:
        batch_op.create_index("idx_team_matches_personnel", ["personnel_id"], unique=False)
        batch_op.create_index(
            "idx_team_matches_project", ["project_id", "match_score"], unique=False
        )

    op.create_table(
        "project_tool_licenses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("total_seats", sa.Integer(), nullable=False),
        sa.Column("cost_per_seat_monthly", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_tool_licenses", schema=None) as batch_op:
        batch_op.create_index("idx_tool_licenses_project", ["project_id"], unique=False)

    op.create_table(
        "scenarios",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "archived",
                "rejected",
                name="scenario_status",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("is_snapshot", sa.Boolean(), nullable=False),
        sa.Column("parent_scenario_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_scenario_id"], ["scenarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenarios_project_id"), ["project_id"], unique=False)

    op.create_table(
        "skill_matrix_entries",
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("skill_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="skill_level",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("wfu_multiplier_standard", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("wfu_multiplier_fast", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("wfu_multiplier_quality", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("dreyfus_level", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "wfu_multiplier_standard >= 0.5 AND wfu_multiplier_quality <= 3.0",
            name="valid_wfu_multiplier",
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skill_matrix_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_matrix_entries_personnel_id"), ["personnel_id"], unique=False
        )

    op.create_table(
        "xp_events",
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("skill_name", sa.String(length=100), nullable=True),
        sa.Column("xp_amount", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "task_completed",
                "early_delivery",
                "new_skill",
                "quality_bonus",
                "mentoring",
                name="xp_reason",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("xp_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_xp_events_personnel_id"), ["personnel_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_xp_events_project_id"), ["project_id"], unique=False)

    op.create_table(
        "llm_sessions",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column(
            "session_type",
            sa.Enum(
                "task_generation",
                "risk_analysis",
                "optimization_prompt",
                "general",
                name="llm_session_type",
                native_enum=False,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_sessions_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_llm_sessions_scenario_id"), ["scenario_id"], unique=False
        )

    op.create_table(
        "project_warnings",
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column(
            "warning_type",
            sa.Enum(
                "capacity",
                "junior_alone",
                "time_risk",
                "language_barrier",
                "budget",
                "license",
                "skill_mismatch",
                "dependency",
                name="warning_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "critical", "warning", "info", name="warning_severity", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project_warnings", schema=None) as batch_op:
        batch_op.create_index(
            "idx_warnings_scenario", ["scenario_id", "is_acknowledged"], unique=False
        )

    op.create_table(
        "scenario_completion_snapshots",
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("p_on_time", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("eac_date", sa.Date(), nullable=False),
        sa.Column("days_delta", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("spi", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("active_risk_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenario_completion_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "idx_completion_snapshots_scenario", ["scenario_id", "computed_at"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("scenario_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "backend",
                "frontend",
                "devops",
                "qa",
                "research",
                "design",
                "pm",
                name="task_category",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "todo",
                "in_progress",
                "review",
                "done",
                "blocked",
                name="task_status",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                name="task_priority",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("tech_stacks", sa.JSON(), nullable=False),
        sa.Column("required_languages", sa.JSON(), nullable=False),
        sa.Column("effort_investigate_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_design_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_implement_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_testing_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_review_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_support_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("effort_total_days", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=True),
        sa.Column("planned_end", sa.Date(), nullable=True),
        sa.Column("actual_start", sa.Date(), nullable=True),
        sa.Column("actual_end", sa.Date(), nullable=True),
        sa.Column("cocomo_size_points", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("position_x", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("position_z", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("llm_analysis", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("idx_tasks_scenario", ["scenario_id"], unique=False)

    op.create_table(
        "tool_seat_assignments",
        sa.Column("tool_license_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tool_license_id"], ["project_tool_licenses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_seat_assignments", schema=None) as batch_op:
        batch_op.create_index("idx_seat_assignments_tool", ["tool_license_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tool_seat_assignments_personnel_id"), ["personnel_id"], unique=False
        )

    op.create_table(
        "resource_assignments",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "wfu_mode",
            sa.Enum("standard", "fast", "quality", name="wfu_mode", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("effective_wfu", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("is_lead", sa.Boolean(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "allocation_pct > 0 AND allocation_pct <= 100", name="valid_assignment_allocation"
        ),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resource_assignments", schema=None) as batch_op:
        batch_op.create_index("idx_assignments_personnel", ["personnel_id"], unique=False)
        batch_op.create_index("idx_assignments_task", ["task_id"], unique=False)

    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "dependency_type",
            sa.Enum(
                "finish_to_start",
                "start_to_start",
                "finish_to_finish",
                name="dependency_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("lag_days", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("task_id != depends_on_task_id", name="no_self_dependency"),
        sa.ForeignKeyConstraint(["depends_on_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_dependencies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_dependencies_depends_on_task_id"),
            ["depends_on_task_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_task_dependencies_task_id"), ["task_id"], unique=False)

    op.create_table(
        "task_progress_logs",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_id", sa.Uuid(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("completion_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("hours_spent", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["personnel_id"], ["personnel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_progress_logs", schema=None) as batch_op:
        batch_op.create_index("idx_progress_task_date", ["task_id", "log_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_task_progress_logs_personnel_id"), ["personnel_id"], unique=False
        )

    # --- Circular FKs added after all tables exist ---
    # projects.active_scenario_id → scenarios.id
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_projects_active_scenario",
            "scenarios",
            ["active_scenario_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # projects.evaluation_id → project_evaluations.id
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_projects_evaluation",
            "project_evaluations",
            ["evaluation_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # project_evaluations.llm_session_id → llm_sessions.id
    with op.batch_alter_table("project_evaluations", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_project_evaluations_llm_session",
            "llm_sessions",
            ["llm_session_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop circular FKs first
    with op.batch_alter_table("project_evaluations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_evaluations_llm_session", type_="foreignkey")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint("fk_projects_evaluation", type_="foreignkey")
        batch_op.drop_constraint("fk_projects_active_scenario", type_="foreignkey")

    with op.batch_alter_table("task_progress_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_progress_logs_personnel_id"))
        batch_op.drop_index("idx_progress_task_date")

    op.drop_table("task_progress_logs")
    with op.batch_alter_table("task_dependencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_dependencies_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_dependencies_depends_on_task_id"))

    op.drop_table("task_dependencies")
    with op.batch_alter_table("resource_assignments", schema=None) as batch_op:
        batch_op.drop_index("idx_assignments_task")
        batch_op.drop_index("idx_assignments_personnel")

    op.drop_table("resource_assignments")
    with op.batch_alter_table("tool_seat_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_seat_assignments_personnel_id"))
        batch_op.drop_index("idx_seat_assignments_tool")

    op.drop_table("tool_seat_assignments")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_tasks_scenario")

    op.drop_table("tasks")
    with op.batch_alter_table("scenario_completion_snapshots", schema=None) as batch_op:
        batch_op.drop_index("idx_completion_snapshots_scenario")

    op.drop_table("scenario_completion_snapshots")
    with op.batch_alter_table("project_warnings", schema=None) as batch_op:
        batch_op.drop_index("idx_warnings_scenario")

    op.drop_table("project_warnings")
    with op.batch_alter_table("llm_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_sessions_scenario_id"))
        batch_op.drop_index(batch_op.f("ix_llm_sessions_project_id"))

    op.drop_table("llm_sessions")
    with op.batch_alter_table("xp_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xp_events_project_id"))
        batch_op.drop_index(batch_op.f("ix_xp_events_personnel_id"))

    op.drop_table("xp_events")
    with op.batch_alter_table("skill_matrix_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_matrix_entries_personnel_id"))

    op.drop_table("skill_matrix_entries")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_project_id"))

    op.drop_table("scenarios")
    with op.batch_alter_table("project_tool_licenses", schema=None) as batch_op:
        batch_op.drop_index("idx_tool_licenses_project")

    op.drop_table("project_tool_licenses")
    with op.batch_alter_table("project_team_matches", schema=None) as batch_op:
        batch_op.drop_index("idx_team_matches_project")
        batch_op.drop_index("idx_team_matches_personnel")

    op.drop_table("project_team_matches")
    with op.batch_alter_table("project_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_memberships_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_memberships_personnel_id"))

    op.drop_table("project_memberships")
    op.drop_table("project_evaluations")
    op.drop_table("personnel_profiles")
    with op.batch_alter_table("personnel_languages", schema=None) as batch_op:
        batch_op.drop_index("idx_personnel_languages")

    op.drop_table("personnel_languages")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_org_id"))

    op.drop_table("projects")
    with op.batch_alter_table("personnel", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_personnel_org_id"))

    op.drop_table("personnel")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_org_id"))

    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
